/**
 * Script: Seed Default AI Personas + Knowledge Base
 * Purpose: Isi tabel ai_agent_personas + rag_documents + rag_chunks dengan data default
 * Usage: npx tsx scripts/seed-ai-defaults.ts
 * Side effects: INSERT ON DUPLICATE KEY UPDATE — idempotent, aman dijalankan berulang
 */

import * as mysql from "mysql2/promise";
import * as crypto from "crypto";
import * as dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, "../.env.local") });

async function getConn() {
  return mysql.createConnection({
    host: process.env.TIDB_HOST,
    port: Number(process.env.TIDB_PORT ?? 4000),
    user: process.env.TIDB_USER,
    password: process.env.TIDB_PASSWORD,
    database: process.env.TIDB_DATABASE,
    ssl: { rejectUnauthorized: false },
  });
}

function chunkText(text: string, size = 800, overlap = 100): string[] {
  const chunks: string[] = [];
  let start = 0;
  while (start < text.length) {
    chunks.push(text.slice(start, start + size));
    start += size - overlap;
  }
  return chunks;
}

// ─── Personas ────────────────────────────────────────────────────────────────

const PERSONAS = [
  {
    id: "persona-default-expert",
    name: "FinArchitect Expert",
    description: "Analis keuangan marketplace yang data-driven. Memberikan insight terstruktur dengan angka dan rekomendasi konkret.",
    tone: "expert",
    isDefault: 1,
    systemPrompt: [
      "Kamu adalah FinArchitect AI, analis keuangan expert untuk seller marketplace Indonesia (Shopee, Tokopedia, TikTok, Lazada).",
      "",
      "## Peran & Gaya",
      "- Analis data keuangan yang presisi dan actionable",
      "- Gunakan bahasa Indonesia profesional, terminologi marketplace yang tepat",
      "- Respons dengan markdown terstruktur: header jelas, bullet points, tabel jika perlu",
      "- Selalu sertakan angka konkret, persentase, dan perbandingan",
      "- Identifikasi anomali dan berikan rekomendasi prioritas",
      "",
      "## Fokus Analisis",
      "- Revenue, HPP (Harga Pokok Penjualan), Net Profit, Gross Margin",
      "- Platform fee breakdown: komisi, biaya transaksi, free shipping, voucher",
      "- ROAS (Return on Ad Spend): efisiensi iklan per SKU dan per marketplace",
      "- HPP margin: identifikasi produk margin negatif/tipis",
      "- Tren bulanan: deteksi penurunan revenue atau kenaikan fee yang abnormal",
      "",
      "## Format Output",
      "Gunakan format:",
      "### [Judul Insight]",
      "**Ringkasan:** [1-2 kalimat]",
      "**Data kunci:** [angka spesifik]",
      "**Rekomendasi:** [langkah konkret 1-3 item]",
      "",
      "Hindari generalisasi. Berdasarkan data aktual dalam laporan.",
    ].join("\n"),
  },
  {
    id: "persona-default-friendly",
    name: "Advisor Ramah",
    description: "Konsultan yang ramah dan mudah dipahami. Cocok untuk seller yang baru memahami laporan keuangan marketplace.",
    tone: "friendly",
    isDefault: 0,
    systemPrompt: [
      "Halo! Kamu adalah Fina, asisten keuangan FinArchitect yang ramah dan mudah dipahami.",
      "",
      "## Cara Kamu Berkomunikasi",
      "- Bahasa Indonesia yang santai tapi profesional",
      "- Jelaskan istilah teknis dengan analogi sederhana",
      "- Beri apresiasi untuk pencapaian, dan dukungan untuk area yang perlu perbaikan",
      "- Hindari jargon yang membingungkan — jika terpaksa pakai, selalu jelaskan",
      "",
      "## Yang Kamu Bantu",
      "- Memahami laporan revenue dan profit marketplace (Shopee, Tokopedia, TikTok, Lazada)",
      "- Menjelaskan arti HPP, biaya platform, dan margin dengan cara yang mudah",
      "- Menemukan produk yang menguntungkan dan yang perlu perhatian",
      "- Memberikan tips praktis untuk meningkatkan profit",
      "",
      "## Gaya Respons",
      "- Mulai dengan ringkasan yang mudah dipahami",
      "- Gunakan analogi jika perlu (biaya platform itu seperti sewa lapak di mall)",
      "- Berikan 2-3 langkah konkret yang bisa langsung dieksekusi",
      "- Akhiri dengan pertanyaan lanjutan yang membantu",
      "",
      "Selalu respons dalam Bahasa Indonesia yang hangat dan encouraging!",
    ].join("\n"),
  },
  {
    id: "persona-default-formal",
    name: "Konsultan Formal",
    description: "Konsultan keuangan dengan pendekatan formal dan terstruktur. Ideal untuk laporan yang akan dipresentasikan ke stakeholder.",
    tone: "formal",
    isDefault: 0,
    systemPrompt: [
      "Anda adalah Konsultan Keuangan FinArchitect dengan pendekatan formal dan metodis untuk analisis marketplace Indonesia.",
      "",
      "## Standar Komunikasi",
      "- Bahasa Indonesia formal dan baku (EYD)",
      "- Struktur analisis: Pendahuluan > Temuan > Analisis > Rekomendasi > Penutup",
      "- Referensikan data dengan presisi (gunakan angka eksak, bukan estimasi)",
      "- Objektif dan netral — tidak ada bias terhadap marketplace tertentu",
      "",
      "## Ruang Lingkup Analisis",
      "1. Pendapatan Bruto — total revenue sebelum biaya",
      "2. Biaya Platform — rincian komisi, biaya transaksi, dan program promosi",
      "3. Harga Pokok Penjualan (HPP) — kontribusi terhadap margin kotor",
      "4. Laba Bersih — setelah seluruh deduksi biaya",
      "5. Efisiensi Iklan (ROAS) — return on ad spend per kanal dan SKU",
      "",
      "## Format Laporan",
      "- Ringkasan Eksekutif (3-5 poin utama)",
      "- Analisis Detail dengan data tabel",
      "- Identifikasi Risiko (margin negatif, fee outlier)",
      "- Rekomendasi Strategis (jangka pendek dan menengah)",
      "",
      "Seluruh respons menggunakan Bahasa Indonesia formal sesuai kaidah EYD.",
    ].join("\n"),
  },
];

// ─── Knowledge Base Documents ────────────────────────────────────────────────

const KB_DOCS: Array<{ title: string; fileName: string; content: string }> = [
  {
    title: "Panduan Biaya Platform Marketplace Indonesia 2025",
    fileName: "biaya-platform-marketplace-2025.md",
    content: [
      "# Panduan Biaya Platform Marketplace Indonesia 2025",
      "",
      "## Shopee",
      "",
      "Komisi Platform: 2.5% - 10.2% tergantung kategori produk.",
      "Biaya Transaksi: 2.18% dari nilai pesanan setelah diskon.",
      "Biaya Pemrosesan Pesanan: Rp1.250 per pesanan berhasil.",
      "",
      "Program Opsional Shopee:",
      "- Free Shipping XTRA: Biaya tambahan 4% - 4.5% dari nilai produk. Shopee menanggung ongkir pembeli.",
      "- Shopee Coins Cashback: 3% - 5% dari nilai produk. Digunakan untuk program reward pembeli.",
      "- Promo XTRA: 1.4% - 2% untuk peserta program promosi khusus Shopee.",
      "",
      "Voucher seller ditanggung penuh oleh seller dan dipotong dari settlement.",
      "Voucher Shopee ditanggung marketplace, tidak mempengaruhi settlement seller.",
      "Settlement Shopee dilakukan H+5 hingga H+7 setelah pesanan selesai.",
      "",
      "## Tokopedia / TikTok Shop",
      "",
      "TikTok Shop menggunakan sistem fee yang mirip dengan Tokopedia setelah merger operasional.",
      "",
      "Komisi Platform Tokopedia: 1% - 8% tergantung kategori.",
      "Dynamic Commission Fee (DCF): 4% - 6% per transaksi dengan maksimum Rp40.000 per item.",
      "Biaya Pemrosesan Pesanan Tokopedia: Rp1.250 per pesanan.",
      "",
      "Seller Mall / Official Store Tokopedia:",
      "- Mall Service Fee: 1.8% dari nilai transaksi",
      "- Maksimum Mall Service Fee: Rp50.000 per transaksi",
      "",
      "Komisi affiliate Tokopedia berkisar 3% - 10% tergantung program dan kategori.",
      "Settlement Tokopedia: H+3 setelah pesanan selesai.",
      "TikTok Shop settlement: bervariasi H+5 hingga H+10.",
      "",
      "## Lazada",
      "",
      "Administrative Fee Lazada: 1.82% flat untuk semua kategori.",
      "Commission Fee Lazada: 2.43% - 22.5% tergantung kategori (naik signifikan November 2025).",
      "Payment Processing Fee Lazada: sekitar 2% dari nilai transaksi.",
      "",
      "Program Opsional Lazada:",
      "- Free Shipping Max: Biaya tambahan sekitar 4% untuk program ongkir gratis.",
      "- LazMall: Seller LazMall mendapat prioritas tapi membayar fee lebih tinggi.",
      "",
      "Affiliate Lazada (LazAffiliates): 3% - 8% tergantung kategori.",
      "Settlement Lazada: H+7 setelah konfirmasi penerimaan pembeli.",
      "",
      "## Perbandingan Fee Total Estimasi",
      "",
      "Shopee reguler: Fee Total 6% - 14%",
      "Shopee dengan Free Shipping dan Coins Cashback: Fee Total 10% - 20%",
      "Tokopedia reguler: Fee Total 6% - 15%",
      "Tokopedia Mall: Fee Total 8% - 17%",
      "Lazada reguler: Fee Total 6% - 26%",
      "",
      "Estimasi sudah termasuk komisi, biaya transaksi, biaya pemrosesan.",
      "Tidak termasuk voucher seller dan biaya iklan.",
    ].join("\n"),
  },
  {
    title: "Panduan HPP dan Margin untuk Seller Marketplace",
    fileName: "panduan-hpp-margin.md",
    content: [
      "# Panduan HPP dan Margin untuk Seller Marketplace",
      "",
      "## Apa Itu HPP (Harga Pokok Penjualan)?",
      "",
      "HPP adalah total biaya yang dikeluarkan untuk menghasilkan atau membeli produk yang dijual. Termasuk:",
      "- Harga beli produk dari supplier",
      "- Biaya packaging (kardus, bubble wrap, selotip)",
      "- Biaya label dan branding",
      "- Biaya quality control jika ada",
      "- Biaya penyimpanan opsional jika diperhitungkan",
      "",
      "Formula HPP per unit: HPP = Harga Beli + Packaging + Label + QC + Penyimpanan",
      "",
      "## Gross Margin vs Net Margin",
      "",
      "Gross Profit = Revenue - HPP",
      "Gross Margin = (Gross Profit / Revenue) x 100%",
      "",
      "Gross margin belum memperhitungkan biaya platform. Menunjukkan seberapa besar markup dari harga pokok.",
      "",
      "Net Profit = Revenue - HPP - Biaya Platform - Voucher Seller - Biaya Iklan",
      "Net Margin = (Net Profit / Revenue) x 100%",
      "",
      "Net margin adalah angka yang paling penting — ini adalah keuntungan sesungguhnya per transaksi.",
      "",
      "## Target Margin yang Sehat per Kategori",
      "",
      "Produk fashion: Gross Margin > 40%, Net Margin > 15%",
      "Produk elektronik: Gross Margin > 20%, Net Margin > 8%",
      "Produk FnB: Gross Margin > 50%, Net Margin > 20%",
      "Produk kecantikan: Gross Margin > 45%, Net Margin > 18%",
      "Produk household: Gross Margin > 35%, Net Margin > 12%",
      "",
      "## Identifikasi Produk Margin Negatif",
      "",
      "Produk dengan net margin negatif berarti seller RUGI setiap kali produk itu terjual.",
      "",
      "Penyebab umum margin negatif:",
      "1. HPP terlalu tinggi dibanding harga jual",
      "2. Biaya platform melebihi ekspektasi",
      "3. Voucher seller terlalu besar",
      "4. Biaya iklan (ads) tidak efisien",
      "",
      "Cara mengatasi margin negatif:",
      "- Naikkan harga jual minimal agar net margin = 0 (Break Even Point)",
      "- Negosiasi ulang harga dari supplier untuk turunkan HPP",
      "- Evaluasi program fee — keluar dari program yang tidak menguntungkan",
      "- Hitung ulang biaya iklan — pastikan ROAS minimal agar tidak rugi",
      "",
      "## Break Even Price",
      "",
      "Break Even Price = HPP dibagi (1 - Total Fee Rate)",
      "",
      "Contoh perhitungan break even:",
      "HPP = Rp50.000",
      "Total Fee Shopee = 12%",
      "Break Even Price = 50.000 / (1 - 0.12) = Rp56.818",
      "",
      "Harga jual HARUS di atas break even price agar tidak rugi. Belum termasuk iklan dan voucher.",
      "",
      "## HPP Multi-SKU dalam Satu Pesanan",
      "",
      "Saat satu pesanan berisi banyak SKU, HPP dikalkulasi per SKU:",
      "Total HPP Pesanan = Jumlah (HPP per unit x Qty per SKU)",
      "Net Profit Pesanan = Revenue Pesanan - Total HPP Pesanan - Biaya Platform Pesanan",
      "",
      "Pastikan HPP setiap SKU sudah ter-input dengan benar di sistem HPP Manager.",
    ].join("\n"),
  },
  {
    title: "Panduan ROAS dan Iklan Marketplace",
    fileName: "panduan-roas-iklan.md",
    content: [
      "# Panduan ROAS dan Iklan Marketplace",
      "",
      "## Apa Itu ROAS?",
      "",
      "ROAS (Return on Ad Spend) mengukur efisiensi pengeluaran iklan.",
      "ROAS = Revenue dari Iklan / Total Spend Iklan",
      "",
      "Contoh: Spend Rp1.000.000, Revenue Rp4.000.000, maka ROAS = 4x.",
      "ROAS 4x artinya setiap Rp1 yang dikeluarkan untuk iklan menghasilkan Rp4 revenue.",
      "",
      "## Target ROAS per Marketplace",
      "",
      "Shopee Ads: ROAS Minimal 3x, Bagus 5x, Excellent 8x",
      "Tokopedia TopAds: ROAS Minimal 3x, Bagus 5x, Excellent 8x",
      "TikTok GMV Max: ROAS Minimal 2x, Bagus 4x, Excellent 6x",
      "Lazada Sponsored: ROAS Minimal 3x, Bagus 5x, Excellent 8x",
      "",
      "Kategori dengan margin rendah membutuhkan ROAS lebih tinggi untuk tetap profit.",
      "",
      "## ROAS Break Even",
      "",
      "ROAS break even adalah ROAS minimum agar iklan tidak mengakibatkan kerugian.",
      "ROAS Break Even = 1 / Net Margin (dalam desimal)",
      "",
      "Contoh: Net Margin 20% maka ROAS Break Even = 1 / 0.20 = 5x",
      "Jika net margin 20%, iklan HARUS menghasilkan minimal ROAS 5x agar tidak rugi.",
      "",
      "## Jenis Iklan per Marketplace",
      "",
      "Shopee Ads:",
      "- Shopee Product Ads: Tampil di hasil pencarian dan halaman kategori",
      "- Shop Ads: Promosikan toko di beranda Shopee",
      "- Discovery Ads: Tampil di rekomendasi produk",
      "- Sistem bidding: CPC (Cost Per Click) atau otomatis",
      "",
      "Tokopedia TopAds:",
      "- Product Ads: Tampil di bagian atas hasil pencarian",
      "- Headline Ads: Banner di halaman utama kategori",
      "- Sistem bidding: CPC dengan bid manual atau otomatis",
      "",
      "TikTok Shop GMV Max:",
      "- GMV Max: Iklan otomatis yang dioptimalkan untuk revenue",
      "- Product Showcase: Tampil di video TikTok",
      "- Live Shopping Ads: Promosi saat seller live",
      "- Karakteristik: ROAS bisa lebih rendah karena target audience lebih luas",
      "",
      "Lazada Sponsored Discovery:",
      "- Sponsored Products: Tampil di hasil pencarian",
      "- Sponsored Brands: Banner merek di halaman kategori",
      "",
      "## Analisis Efisiensi Iklan per SKU",
      "",
      "Metrik penting per SKU:",
      "- CPA (Cost per Acquisition) = Total Spend / Total Konversi",
      "- CTR (Click Through Rate) = Klik / Tayangan x 100%",
      "- Conversion Rate = Konversi / Klik x 100%",
      "",
      "SKU yang bagus untuk diiklankan:",
      "- Net margin tinggi (lebih dari 20%)",
      "- Conversion rate lebih dari 2%",
      "- Review produk bagus (lebih dari 4.5 bintang)",
      "- Stok aman untuk scale",
      "",
      "SKU yang sebaiknya tidak diiklankan:",
      "- Net margin kurang dari 15% (ROAS break even terlalu tinggi)",
      "- Stok terbatas",
      "- Review produk rendah",
      "",
      "## Tips Optimasi ROAS",
      "",
      "1. Mulai dengan bid rendah — naikkan bertahap 10-20% per minggu jika ROAS baik",
      "2. Negative keywords di Shopee/Tokopedia — exclude keyword yang tidak relevan",
      "3. Jadwal iklan — matikan iklan di jam dengan konversi rendah",
      "4. Budget harian — batasi agar tidak overspend di awal",
      "5. Monitor mingguan — evaluasi ROAS per SKU setiap minggu",
      "6. Hentikan iklan SKU dengan ROAS di bawah break even setelah 2 minggu",
      "7. Scale up budget 20-30% per minggu untuk SKU yang ROAS lebih dari 5x",
    ].join("\n"),
  },
  {
    title: "Terminologi Keuangan Marketplace Indonesia",
    fileName: "terminologi-keuangan-marketplace.md",
    content: [
      "# Terminologi Keuangan Marketplace Indonesia",
      "",
      "## Revenue (Pendapatan Kotor)",
      "Total nilai penjualan sebelum dikurangi biaya apapun.",
      "Angka yang terlihat di dashboard marketplace sebagai Total Penjualan atau Total Revenue.",
      "",
      "## HPP (Harga Pokok Penjualan)",
      "Biaya untuk menghasilkan atau membeli produk. Dalam bahasa Inggris disebut COGS (Cost of Goods Sold).",
      "Semakin rendah HPP relatif terhadap harga jual, semakin tinggi margin.",
      "",
      "## Gross Profit (Laba Kotor)",
      "Revenue dikurangi HPP. Belum memperhitungkan biaya platform, iklan, dan biaya operasional lainnya.",
      "",
      "## Net Profit (Laba Bersih)",
      "Revenue dikurangi semua biaya: HPP, biaya platform, voucher seller, biaya iklan.",
      "Ini adalah keuntungan sesungguhnya.",
      "",
      "## Settlement Amount",
      "Jumlah uang yang benar-benar diterima seller dari marketplace setelah semua pemotongan biaya platform.",
      "",
      "## Komisi Platform",
      "Persentase yang diambil marketplace dari setiap penjualan berhasil. Bervariasi per kategori.",
      "",
      "## Biaya Transaksi (Transaction Fee)",
      "Biaya pemrosesan pembayaran dari marketplace. Di Shopee: 2.18%.",
      "",
      "## Biaya Pemrosesan Pesanan (Order Processing Fee)",
      "Biaya flat per pesanan yang berhasil. Umumnya Rp1.250 per pesanan di Shopee dan Tokopedia.",
      "",
      "## Free Shipping Subsidy (Subsidi Ongkir)",
      "Biaya yang dibebankan ke seller untuk program gratis ongkir. Shopee XTRA: 4-4.5%.",
      "",
      "## Voucher Seller",
      "Diskon yang diberikan seller kepada pembeli. Ditanggung penuh oleh seller dan dipotong dari settlement.",
      "",
      "## Voucher Marketplace",
      "Diskon dari marketplace. Ditanggung marketplace, tidak mempengaruhi settlement seller.",
      "",
      "## Dynamic Commission Fee (DCF)",
      "Sistem komisi Tokopedia yang dinamis berdasarkan nilai transaksi, dengan batas maksimum per item.",
      "",
      "## ROAS (Return on Ad Spend)",
      "Rasio revenue yang dihasilkan dari iklan dibagi total biaya iklan.",
      "ROAS 4x = setiap Rp1 iklan menghasilkan Rp4 revenue.",
      "",
      "## CTR (Click Through Rate)",
      "Persentase orang yang mengklik iklan dari total yang melihat iklan.",
      "CTR tinggi = iklan relevan dan menarik untuk audiens.",
      "",
      "## Conversion Rate",
      "Persentase pengunjung atau klik yang melakukan pembelian.",
      "Conversion rate tinggi = produk menarik dan harga kompetitif.",
      "",
      "## CPA (Cost Per Acquisition)",
      "Biaya iklan yang dibutuhkan untuk mendapatkan 1 pembelian.",
      "CPA = Total Spend / Total Konversi.",
      "",
      "## Break Even Point",
      "Titik impas — harga jual minimum agar tidak rugi setelah HPP dan biaya platform.",
      "",
      "## Net Margin",
      "Persentase keuntungan bersih dari total revenue.",
      "Net Margin 15% = dari Rp100 pendapatan, Rp15 adalah keuntungan bersih.",
      "",
      "## Status Pesanan",
      "",
      "Pesanan Selesai (Completed): Pembeli sudah konfirmasi terima barang.",
      "Revenue dari pesanan ini sudah final dan masuk hitungan laporan.",
      "",
      "Pesanan Dibatalkan (Cancelled): Pesanan dibatalkan sebelum dikirim.",
      "Revenue tidak dihitung, tidak ada biaya platform.",
      "",
      "Pesanan Retur (Return): Barang dikembalikan pembeli setelah diterima.",
      "Revenue dikembalikan ke pembeli, biaya platform mungkin tidak dikembalikan.",
      "",
      "Failed Delivery: Paket gagal terkirim dan dikembalikan ke seller.",
      "Status penting untuk rekonsiliasi laporan.",
      "",
      "## Istilah Upload Data",
      "",
      "File Pesanan (Order File): Export data pesanan dari marketplace.",
      "Berisi detail produk, SKU, qty, harga.",
      "",
      "File Pendapatan (Income atau Settlement File): Export data pendapatan dari marketplace.",
      "Source of truth untuk amount yang diterima — termasuk semua pemotongan biaya.",
      "",
      "Rekonsiliasi (Reconciliation): Proses mencocokkan data pesanan dengan data pendapatan.",
      "Menghasilkan laporan akurat per order.",
      "",
      "SKU (Stock Keeping Unit): Kode unik per varian produk.",
      "Contoh: BAJU-MERAH-L atau ABC123-HITAM.",
    ].join("\n"),
  },
  {
    title: "Tips Optimasi Revenue Seller Marketplace",
    fileName: "tips-optimasi-revenue.md",
    content: [
      "# Tips Optimasi Revenue Seller Marketplace",
      "",
      "## 1. Manajemen Harga yang Efektif",
      "",
      "Hitung Harga Jual Minimum sebelum menetapkan harga:",
      "Harga Minimum = HPP / (1 - Fee Rate - Target Margin)",
      "",
      "Contoh: HPP Rp30.000, Fee Shopee 10%, Target Net Margin 15%",
      "Harga Minimum = 30.000 / (1 - 0.10 - 0.15) = Rp40.000",
      "",
      "Strategi harga yang efektif:",
      "- Psychological pricing: Rp49.000 terasa lebih murah dari Rp50.000",
      "- Bundle pricing: Jual 2 pcs dengan harga lebih murah untuk naikkan AOV (Average Order Value)",
      "- Flash sale: Turunkan harga tapi hitung ulang margin — pastikan masih profit",
      "",
      "## 2. Optimasi HPP",
      "",
      "Negosiasi Supplier:",
      "- Beli dalam jumlah lebih besar untuk dapat harga lebih murah",
      "- Minta harga khusus untuk repeat order atau pembayaran tunai",
      "- Bandingkan minimal 3 supplier sebelum commit",
      "",
      "Efisiensi Packaging:",
      "- Gunakan packaging sesuai ukuran produk, jangan buang-buang space",
      "- Beli packaging dalam jumlah besar untuk harga lebih murah",
      "- Pertimbangkan packaging custom branded untuk produk premium",
      "",
      "## 3. Kelola Biaya Platform",
      "",
      "Evaluasi Program Fee Secara Berkala:",
      "- Hitung apakah program Free Shipping menguntungkan",
      "- Evaluasi program Coins Cashback: apakah meningkatkan repeat buyer?",
      "- Keluar dari program yang tidak menguntungkan berdasarkan data",
      "",
      "Voucher Seller yang Efektif:",
      "- Voucher minimum pembelian lebih efektif dari diskon flat kecil",
      "- Hitung biaya voucher sebagai bagian dari biaya marketing",
      "- Evaluasi apakah voucher meningkatkan AOV atau hanya memangkas margin",
      "",
      "## 4. Strategi Iklan yang Profit",
      "",
      "Mulai dari SKU Terbaik:",
      "- Pilih 20% SKU dengan margin tertinggi untuk diiklankan",
      "- Pastikan ROAS lebih dari break even sebelum scale budget",
      "",
      "Alokasi Budget Iklan sebagai persentase revenue:",
      "- Fase Baru (toko kurang dari 6 bulan): 10-20% revenue",
      "- Fase Pertumbuhan: 7-15% revenue",
      "- Fase Mature: 5-10% revenue",
      "",
      "## 5. Rekonsiliasi Laporan Rutin",
      "",
      "Rekonsiliasi penting untuk:",
      "- Mendeteksi biaya platform yang tidak sesuai (anomali fee)",
      "- Memastikan semua pesanan sudah ter-settlement dengan benar",
      "- Menghitung profitabilitas per SKU, per marketplace, dan per periode",
      "",
      "Jadwal Rekonsiliasi yang Disarankan:",
      "- Harian: Monitor jumlah pesanan masuk dan status",
      "- Mingguan: Cek ROAS iklan dan update HPP jika ada perubahan harga beli",
      "- Bulanan: Laporan lengkap revenue, profit, dan analisis per SKU",
      "",
      "## 6. Manajemen Stok",
      "",
      "Hindari Stockout:",
      "- Produk habis berarti kehilangan ranking dan review organik",
      "- Pertahankan buffer stok minimal 30 hari untuk produk terlaris",
      "",
      "Hindari Overstock:",
      "- Modal tertahan di stok = biaya opportunity cost",
      "- Gunakan flash sale atau bundle untuk likuidasi stok lama",
      "",
      "## 7. Optimalkan Listing Produk",
      "",
      "Foto Produk:",
      "- Minimal 5 foto berkualitas tinggi",
      "- Sertakan foto produk dipakai atau digunakan",
      "- Infografis yang menjelaskan fitur dan keunggulan",
      "",
      "Deskripsi Produk:",
      "- Jawab pertanyaan umum pembeli di deskripsi",
      "- Sertakan spesifikasi lengkap",
      "- Update deskripsi berdasarkan review negatif yang sering muncul",
      "",
      "Keyword Optimization:",
      "- Riset keyword dengan volume pencarian tinggi",
      "- Masukkan di judul, deskripsi, dan atribut produk",
    ].join("\n"),
  },
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const conn = await getConn();
  console.log("✓ DB connected");

  try {
    // ── Seed Personas ──
    console.log("\n[1/2] Seeding AI Agent Personas...");
    for (const p of PERSONAS) {
      await conn.execute(
        `INSERT INTO ai_agent_personas (id, name, description, system_prompt, tone, is_default, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, NOW(), NOW())
         ON DUPLICATE KEY UPDATE
           name = VALUES(name),
           description = VALUES(description),
           system_prompt = VALUES(system_prompt),
           tone = VALUES(tone),
           is_default = VALUES(is_default),
           updated_at = NOW()`,
        [p.id, p.name, p.description ?? null, p.systemPrompt, p.tone, p.isDefault]
      );
      console.log(`  ✓ ${p.name} (tone=${p.tone}, default=${p.isDefault === 1})`);
    }

    // ── Seed Knowledge Base ──
    console.log("\n[2/2] Seeding Knowledge Base Documents...");
    for (const doc of KB_DOCS) {
      const docId = `kb-${doc.fileName.replace(/[^a-z0-9]/gi, "-").slice(0, 32)}`;
      const chunks = chunkText(doc.content);

      // Delete existing chunks for idempotency
      await conn.execute(`DELETE FROM rag_chunks WHERE document_id = ?`, [docId]);

      // Upsert document
      await conn.execute(
        `INSERT INTO rag_documents (id, title, file_name, char_count, chunk_count, uploaded_at)
         VALUES (?, ?, ?, ?, ?, NOW())
         ON DUPLICATE KEY UPDATE
           title = VALUES(title),
           char_count = VALUES(char_count),
           chunk_count = VALUES(chunk_count),
           uploaded_at = NOW()`,
        [docId, doc.title, doc.fileName, doc.content.length, chunks.length]
      );

      // Insert chunks
      for (let i = 0; i < chunks.length; i++) {
        const chunkId = `${docId}-c${String(i).padStart(3, "0")}`;
        await conn.execute(
          `INSERT INTO rag_chunks (id, document_id, chunk_index, content) VALUES (?, ?, ?, ?)`,
          [chunkId, docId, i, chunks[i]]
        );
      }

      console.log(`  ✓ "${doc.title}" → ${chunks.length} chunks`);
    }

    console.log("\n✅ Seed selesai!");
    console.log("\nPersona:");
    PERSONAS.forEach((p) =>
      console.log(`  - ${p.name} (tone=${p.tone}, default=${p.isDefault === 1})`)
    );
    console.log("\nKnowledge Base:");
    KB_DOCS.forEach((d) => console.log(`  - ${d.title}`));
  } finally {
    await conn.end();
  }
}

main().catch((e) => {
  console.error("Seed gagal:", e);
  process.exit(1);
});
